#!/bin/bash
# Supervised Training Setup Guide

echo "🎯 Setting up Supervised Training for ABM EJ Logs"
echo "================================================="

echo ""
echo "STEP 1: Add EJ logs for unsupervised processing"
echo "---------------------------------------------"
echo "Put your EJ log files in:"
echo "  ./data/input/ABM250EJ_YYYYMMDD.txt"
echo ""
echo "Example:"
echo "  cp /path/to/your/logs/ABM250EJ_20250726.txt ./data/input/"

echo ""
echo "STEP 2: Process the logs (automatic)"
echo "-----------------------------------"
echo "The system will automatically:"
echo "  - Process the logs"
echo "  - Detect anomalies using unsupervised ML"
echo "  - Store sessions in the database"

echo ""
echo "STEP 3: Label the anomalies"
echo "-------------------------"
echo "1. Go to: http://localhost/expert-labeling"
echo "2. Review detected anomalies"
echo "3. Label them as:"
echo "   - 'normal' (false positive)"
echo "   - 'dispense_failure'"
echo "   - 'hardware_error'"
echo "   - 'timeout_error'"
echo "   - etc."

echo ""
echo "STEP 4: Train supervised model"
echo "-----------------------------"
echo "1. After labeling at least 10 anomalies"
echo "2. Go to: http://localhost/expert-labeling"
echo "3. Click 'Train Supervised Model'"
echo ""
echo "OR use API:"
echo "curl -X POST http://localhost/api/v1/expert/train-supervised"

echo ""
echo "STEP 5: Monitor training"
echo "----------------------"
echo "Watch logs for training progress:"
echo "docker logs -f abm-ml-api | grep -i 'supervised.*training'"
echo ""
echo "TROUBLESHOOTING: If you get 502 Bad Gateway:"
echo "1. Check containers: docker ps"
echo "2. Restart services: docker compose down && docker compose up -d"
echo "3. Wait 30 seconds for startup"
echo "4. Test direct API: curl http://localhost:8000/api/v1/continuous-learning/status"
echo "5. Test via nginx: curl http://localhost/api/v1/continuous-learning/status"

echo ""
echo "Current Status:"
echo "==============="
echo "EJ files in input directory:"
ls -la ./data/input/*.txt 2>/dev/null | wc -l | xargs echo "  Count:"

echo ""
echo "Database sessions:"
echo "  Check at: http://localhost/overview"

echo ""
echo "Ready for supervised training when you have:"
echo "  ✓ Processed EJ logs in database"  
echo "  ✓ At least 10 expert labels"
echo "  ✓ Mixed labels (normal + various anomaly types)"
