global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/v1/metrics'
    
  - job_name: 'anomaly-detector'
    static_configs:
      - targets: ['anomaly-detector:9091']
    metrics_path: '/metrics'
