FROM flyway/flyway:9

# Install PostgreSQL 15 client and bash
RUN apt-get update && \
    apt-get install -y wget gnupg2 lsb-release && \
    echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y postgresql-client-15 bash && \
    apt-get remove -y postgresql-client-12 && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*