name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connect to DigitalOcean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 64.227.16.180
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e

            echo "➡ Pulling latest code..."
            cd /home/${{ secrets.DROPLET_USER }}/Capstone-Project

            echo "⚠ Removing dashboard build if present..."
            rm -rf abm-anomaly-ml-first/services/dashboard/build

            if [ -f abm-anomaly-ml-first/.env.production ]; then
              echo "⚠ Removing existing .env.production to avoid git conflict..."
              rm abm-anomaly-ml-first/.env.production
            fi

            git reset --hard
            git pull origin main

            echo "➡ Creating fresh .env.production file..."
            cat <<EOF > abm-anomaly-ml-first/.env.production
            POSTGRES_USER=abm_user
            POSTGRES_PASSWORD=secure_ml_password123
            POSTGRES_DB=abm_ml_db
            POSTGRES_HOST=postgres
            REDIS_HOST=redis
            REDIS_PASSWORD=redis_ml_password123
            JWT_SECRET=your_jwt_secret_key_ml_first
            ANOMALY_THRESHOLD=0.7
            MODEL_UPDATE_INTERVAL=3600
            LOG_LEVEL=INFO
            BERT_MODEL=bert-base-uncased
            API_HOST=0.0.0.0
            API_PORT=8000
            REACT_APP_API_URL=http://64.227.16.180:3000
            EOF

            echo "➡ Setting ownership (fix any permission issues)..."
            sudo chown -R $USER:$USER /home/${{ secrets.DROPLET_USER }}/Capstone-Project

            echo "➡ Running Docker Compose..."
            cd abm-anomaly-ml-first

            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production down
            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production build --build-arg REACT_APP_API_URL=http://64.227.16.180:3000
            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production up -d

            echo "✅ Deployment complete."
