name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('abm-anomaly-ml-first/services/dashboard/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dashboard Dependencies (CI mode)
        working-directory: ./abm-anomaly-ml-first/services/dashboard
        run: npm ci

      - name: Build Dashboard Locally
        working-directory: ./abm-anomaly-ml-first/services/dashboard
        run: npm run build

      - name: Restructure build for /dashboard path
        working-directory: ./abm-anomaly-ml-first/services/dashboard
        run: |
          mkdir -p build/dashboard
          mv build/static build/dashboard/
          mv build/index.html build/dashboard/
          mv build/asset-manifest.json build/dashboard/ || true
          mv build/favicon.ico build/dashboard/ || true
          mv build/logo192.png build/dashboard/ || true
          mv build/logo512.png build/dashboard/ || true
          mv build/manifest.json build/dashboard/ || true
          mv build/robots.txt build/dashboard/ || true

      - name: Connect to DigitalOcean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 64.227.16.180
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e

            echo "➡ Pulling latest code..."
            cd /home/${{ secrets.DROPLET_USER }}/Capstone-Project

            if [ -f abm-anomaly-ml-first/.env.production ]; then
              echo "⚠ Removing existing .env.production to avoid git conflict..."
              rm abm-anomaly-ml-first/.env.production
            fi

            git reset --hard
            git pull origin main

            echo "➡ Starting deployment..."
            cd /home/${{ secrets.DROPLET_USER }}/Capstone-Project/abm-anomaly-ml-first

            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production pull
            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production down
            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production up -d --build

            echo "✅ Deployment complete."
