name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connect to DigitalOcean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 64.227.16.180
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e

            echo "➡ Pulling latest code..."
            cd /home/$USER/Capstone-Project

            echo "⚠ Removing dashboard build if present..."
            rm -rf abm-anomaly-ml-first/services/dashboard/build

            if [ -f abm-anomaly-ml-first/.env.production ]; then
              echo "⚠ Backing up existing .env.production..."
              cp abm-anomaly-ml-first/.env.production abm-anomaly-ml-first/.env.production.backup
            fi

            git reset --hard
            git pull origin main

            echo "➡ Ensuring .env.production is configured for production..."
            # The .env.production file is now managed in the repository
            # Just need to set the correct API URL for this deployment
            sed -i 's|REACT_APP_API_URL=.*|REACT_APP_API_URL=http://64.227.16.180/api|g' abm-anomaly-ml-first/.env.production

            echo "➡ Setting ownership (fix any permission issues)..."
            sudo chown -R $USER:$USER /home/$USER/Capstone-Project

            echo "➡ Running deployment with new architecture..."
            cd abm-anomaly-ml-first

            # Make sure deploy script is executable
            chmod +x deploy.sh

            # Stop any existing deployment
            ./deploy.sh production down || true

            # Build and start with production configuration
            ./deploy.sh production build
            ./deploy.sh production up

            echo "✅ Deployment complete using new flexible architecture."
            echo "➡ Checking service status..."
            ./deploy.sh production status
