name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connect to DigitalOcean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 64.227.16.180
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e

            echo "➡ Pulling latest code..."
            cd /home/${{ secrets.DROPLET_USER }}/Capstone-Project

            # ⚠ Clean up existing dashboard build artifacts (avoids permission errors)
            echo "⚠ Removing old dashboard build folder (if any)..."
            rm -rf abm-anomaly-ml-first/services/dashboard/build

            # Remove .env.production if exists
            if [ -f abm-anomaly-ml-first/.env.production ]; then
              echo "⚠ Removing existing .env.production to avoid git conflict..."
              rm abm-anomaly-ml-first/.env.production
            fi

            git reset --hard
            git clean -fd
            git pull origin main

            echo "➡ Creating .env.production file..."
            cat <<EOF > abm-anomaly-ml-first/.env.production
            POSTGRES_USER=abm_user
            POSTGRES_PASSWORD=secure_ml_password123
            POSTGRES_DB=abm_ml_db
            REACT_APP_API_URL=http://64.227.16.180:3000/api/
            EOF

            echo "➡ Starting Docker Compose build and deployment..."
            cd abm-anomaly-ml-first

            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production down
            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production build --build-arg REACT_APP_API_URL=http://64.227.16.180:3000/api/
            docker compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production up -d

            echo "✅ Deployment complete."
