name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Mark repo as safe for Git
        run: git config --global --add safe.directory /home/***/Capstone-Project
      - name: Connect to DigitalOcean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 64.227.16.180
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -e

            echo "➡ Pulling latest code..."
            cd /home/${{ secrets.DROPLET_USER }}/Capstone-Project
            git reset --hard
            git pull origin main

            echo "➡ Using Docker Compose with Flyway for migrations..."
            docker-compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production pull
            docker-compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production down
            docker-compose -f docker-compose.yml -f docker-compose-flyway.yml --env-file .env.production up -d --build

            echo "✅ Deployment complete."
